### ISSUE TITLE
Allow sending zero length message

### ISSUE THREAD

**Issue by NickCao** [PlatformLab/HomaModule#25]
zero length message might sound like an unplausible idea, but as homa is built around the notion of request/response (RPC) style communication, a zero length message serves perfectly as an ACK.

**Comment by johnousterhout** [comment]
I finally found time to take a look at this. I started implementing support for zero-length messages, but they create a lot of complexity and special cases. For example, a zero-length message appears to be fully transmitted (there are no bytes left to send) even when no packets have been sent. My conclusion is that this feature isn't worth the extra complexity (and slight additional execution time) that it incurs for Homa. A zero-length message will end up getting padded because of the minimum packet size, so it doesn't actually save any bytes on the wire. Thus, a one-byte message will work just as well for an ACK as a zero-byte message.
