### ISSUE TITLE
cp_* test code questions and logs/ availability?

### ISSUE THREAD

**Issue by joft-mle** [PlatformLab/HomaModule#46]
Hi Team HOMA, hi @johnousterhout ,

Preamble: _This is not any issue with the HomaModule. Instead this entry is about usage/knowledge questions regarding test code and results. So if I should move the following to a different communication channel, I'm happy to do so. Please advice._

The questions are:

1. Why do the associated HOMA and TCP experiments, the 1:N nodes experiments in `cp_basic`, mostly use different numbers of max. outstanding requests? `homa_client_rpc_tput` uses the default (from cperf.py) of 200. However, `tcp_client_rpc_tput` uses 100 by direct definition in `cp_basic`. The situation is similar for `*_client_tput` (50 vs 20) and `*_server_rpc_tput` (10 vs 50). Just the experiemts `*_server_tput` use the same number (5) for all protocols. **What is the reason for this asymmetry?** `cp_vs_tcp` (in contrast to `cp_basic`) uses 200 outstanding requests (default - or what is specified with `--client-max`) _in any case_.

2. The same question as above arises for the number of client/server ports, for example: In `cp_basic` TCP servers run with 16 ports, where as Homa servers run just with 6. This is in contrast to the number of client ports, which 9 in both cases. **Is my assumption correct, that this number of ports, and also the number of, for example, `port_threads` is a result of elaborations what the "best" scenario is for a certain cluster (the CloudLab cluster, in this case)?** And this is not only true for `cp_basic`, but also for any `cp_*` experiments using defaults from `cperf.py`, which seem to also show "asymmetry" between protocols (e.g. Homa server ports 3 and TCP server ports 8)?

3. I know, the following may be a "answer: it depends" type of question - on potentially multiple levels: I wonder, if you happen to have results of the experiments in `cp_basic` (and `cp_vs_tcp`) for a 10GbE network? Would it be possible to get the `logs/` output(s)? Or do you have an educated "guess" what to expect - out of 10GbE network? Say, we have 4 nodes and especially do one of these throughput tests with "large messages" (either 1 client to multiple servers (`*_client_tput`) or 1 server to multiple clients (*_server_tput)). What Gbit/s value(s) should one expect?

4. Would it be possible to get a "typical" `logs/` output for `cp_basic` and `cp_vs_tcp` from runs on the "cloudlab" 25GbE cluster setup?

**Comment by johnousterhout** [comment]
It's fine to post questions here; here are answers to your questions:

1. I think I was trying to pick parameters for each protocol and experiment that provided the best possible performance for that protocol.

2. Yes, in this case I was definitely optimizing each protocol. In TCP, only one thread can safely read from a single port, so it uses lots of ports with one thread each. Homa can allow multiple threads to share a single socket, so it uses a smaller number of ports, with more threads on each (having multiple threads per port is advantageous because it provides better load balancing).

3. I haven't done any measurements on 10 Gbps networks. But I would expect that both TCP and Homa would have an easier time delivering full network bandwidth at 10 Gbps than 25 Gbps (more available CPU time per bit of network traffic). 
Would it be possible to get a "typical" logs/ output for cp_basic and cp_vs_tcp from runs on the "cloudlab" 25GbE cluster setup?

4. I'm attaching a tar file with 4 directories containing logs and reports. The directories n10_mtu1500 and n10_mtu3000 contains cp_vs_tcp output (using different MTUs), and basic_n10_mtu1500 and basic_n10_mtu3000  contain cp_basic output. Both used 10 nodes running on a 25 Gbps network.

I'm going to close this issue, but feel free to reopen if you have additional questions.

-John-

[logs.tar.gz](https://github.com/PlatformLab/HomaModule/files/12769860/logs.tar.gz)

**Comment by johnousterhout** [comment]
I've responded to this issue a couple of times, but recently got bounce messages suggesting that my response might not have gotten through (perhaps the .gz file is too large?). See the github Web site for my full response. But in addition, I've put the tar file on my Google Drive with public access:

https://drive.google.com/file/d/1SB2StdoHOrBWwzNTUIxXb3_fhScJAmGU/view?usp=sharing

So, if you didn't already receive it, you can get it from there. In any case, can you let me know that you've received the logs and reports so that I can delete the Google Drive file?

Thanks.

-John-

**Comment by joft-mle** [comment]
Hi @johnousterhout ,

thank you for your answers and attaching the 25G logs! To me it looks like the attached `.tar` file did make it through (working link on web site and in mail notification). I was able to download and open it without issues. Thanks!
