### ISSUE TITLE
Homa's Maximum Message Length Modification

### ISSUE THREAD

**Issue by amjal** [PlatformLab/HomaModule#48]
The maximum length of a message in Homa is set by the HOMA_MAX__MESSAGE_LENGTH macro defined in homa.h. In previous builds of the module, particularly for kernel version 5.17.7, I could just change the macro value, and it worked with larger messages. 

With the newest build, however, there is an assertion error I get from this line: 
```
#if !defined(__cplusplus)
_Static_assert(sizeof(struct homa_recvmsg_args) >= 96,
        "homa_recvmsg_args shrunk");
_Static_assert(sizeof(struct homa_recvmsg_args) <= 96,
        "homa_recvmsg_args grew");
#endif
```
I appreciate it if you explain to me why this limit is there in the first place. Is this an implementation limitation? Or is just placed for performance optimization? What is a safe way of modifying it? If these are answered somewhere in the documentation, please just direct me towards them. Thanks.

**Comment by johnousterhout** [comment]
Hmmm, interesting point. This problem arose because homa_recvmsg_args
structs now contain an array of buffer pointers, which is proportional to
HOMA_MAX_MESSAGE_LENGTH.

I added the assertions on the recommendation of Dan Manjarres (cc-ed here);
I believe the reasoning is that changing the size of the struct is likely
to cause software breakage (e.g. existing application binaries will no
longer work with a new transport implementation) so this shouldn't be done
without careful thought. That said, I think it should be safe for you to
change the value 96 in the assertions to reflect the new larger
HOMA_MAX_MESSAGE_LENGTH or even comment out the assertions, as long as you
are careful to recompile all of your applications.

-John-

**Comment by amjal** [comment]
Thanks for the explanation. Commenting out the assertion and recompiling works.
