### ISSUE TITLE
Poor behavior of RSS

### ISSUE THREAD

**Issue by zhongjiechen97** [PlatformLab/HomaModule#59]
Hi John! I found that Homa's use of RSS does not seem to be good? I'm not sure if it's because of my configuration. For example, I use 3 machines as clients and 1 machine as server (xl170 in Cloudlab).
Client command: 
```shell
sudo ./cp_node client --protocol homa --ports 9 --port-receivers 1 --server-ports 6 --client-max 10 --workload 100 --first-server 0
```
Server command: 
```shell
sudo ./cp_node server --protocol homa --ports 6 --port-threads 3
```
However, through command:
```shell
sudo ethtool -S ens1f1np1 | grep -E 'rx[0-9]+_packets' 
```
I observed that only 3 queues are receiving packets. For comparison, I tried running TCP with the same parameters and I found that almost all queues had received packets.

I would be extremely grateful if you could provide some insight!

**Comment by pmo73** [comment]
Hello @zhongjiechen97 ,
this can most likely be explained by the fact that the network cards cannot do RSS for the Homa protocol because they do not know the protocol. I also observed this during investigations for my master thesis and therefore implemented an RSS for the Homa protocol for a smart NIC. The default for most network cards is therefore that if they do not know the transport protocol, they simply make an RSS based on the IP address. Since you have 2 clients here, I would assume that 1 client is assigned to each RX queue and the third RX queue is created by your SSH connection. What the Homa kernel module does, however, is an RPS, or RFS, which redistributes the packets in software. This should be noticeable in the utilization of the CPU. Here you should probably see a load in the SoftIRQ for more than the 3 cores. For TCP, the network cards can run RSS normally due to the IP address and TCP ports, so the use of the RX queues is different here. I hope I could help you and provide an explanation.

**Comment by zhongjiechen97** [comment]
> Hello @zhongjiechen97 , this can most likely be explained by the fact that the network cards cannot do RSS for the Homa protocol because they do not know the protocol. I also observed this during investigations for my master thesis and therefore implemented an RSS for the Homa protocol for a smart NIC. The default for most network cards is therefore that if they do not know the transport protocol, they simply make an RSS based on the IP address. Since you have 3 clients here, I would assume that 1 client is assigned to each RX queue. What the Homa kernel module does, however, is an RPS, or RFS, which redistributes the packets in software. This should be noticeable in the utilization of the CPU. Here you should probably see a load in the SoftIRQ for more than the 3 cores. For TCP, the network cards can run RSS normally due to the IP address and TCP ports, so the use of the RX queues is different here. I hope I could help you and provide an explanation.

@pmo73 Ah, that makes sense! Thanks for your explanation! Let me guess, your RSS implementation should be able to bring some performance gains for Homa, right?

**Comment by zhongjiechen97** [comment]
I noticed that Homa's headers are designed to mimic TCP's headers to take advantage of TSO offloading, I originally thought this should also work for RSS, :).

**Comment by zhongjiechen97** [comment]
> Yes the implementation of RSS has shown a significant impact, however I only have 2 nodes in my test setup which amplifies the effect. The fact that Homa can also use the support for TSO depends heavily on the network card. The Mellanox network cards seem to implement TSO so generically that they do not need to check the type of protocol. On the other hand, Intel network cards like XL710 do not support TSO for Homa.

Helpful information, thanks!

**Comment by johnousterhout** [comment]
I plan to solve the RSS problems in the near future by modifying Homa so that it "hijacks" the TCP protocol. Homa packets will actually be transmitted as TCP packets (i.e. using the TCP protocol type for IP), so that RSS will work better and TSO will work with all NICs. Then, on the receiver side, Homa will "steal" the packets by from TCP (interposing at GRO level).

**Comment by ryankosta** [comment]
IIRC from when I wrote a protocol, RSS for mellanox NICs (cx4) does check the protocol ID, but it does work fine if the protocol ID is right and the length field is valid (I did this with UDP mimicking though).

**Comment by johnousterhout** [comment]
My experience with Mellanox NICs (ConnectX-5) is that they will do RSS for
protocols other than TCP, but they use only the host field (not the ports).
This significantly reduces the benefits of RSS.

-John-
