### ISSUE TITLE
SPLIT_64 missing again

### ISSUE THREAD

**Issue by breakertt** [PlatformLab/HomaModule#66]
> This line shouldn't be removed. 

 _Originally posted by @breakertt in [89b1e99](https://github.com/PlatformLab/HomaModule/commit/89b1e9963b4729e71450ae76b8ee1168550d4ce4#r150459185)_

**Comment by breakertt** [comment]
```
#define SPLIT_64(value) (int) (((__u64) (value)) >> 32), (int) (((__u64) (value)) & 0xffffffff)
```
was removed again in `timetrace.h` after commit 89b1e99, which leads to a compilation failure.

**Comment by johnousterhout** [comment]
Drat; sorry about that. I will push a fix shortly. This keeps happening because I do my testing with a modified Linux kernel, one of whose header files includes a kernel version of timetrace.h that defines SPLIT_64. Thus it compiled for me. I don't currently have an easy way to compile Homa with an "out of the box" kernel... I need to fix that.
